const possibleTitles = [
  "The Orate Gatsby 🎩",
  "GENESIS 🌌",
  "Unfanged Noumena 🧠",
  "The Catcher in the gye ⚾",
  "ECCLESIASTES 📜",
  "L'histoire de l'oeil 👁️",
  "L'histoire de d'eau 💧",
  "CIGCIGCIG 🚬",
  "kafkaesque 🦟",
  "CANDIDE 🍭",
  "Kolmogorov Complexity 🧮",
  "Cig attention is all you need 🧠",
  "RIP PAPPA 🙏",
  "Call me Ishmael 🐳",
  "mylady 🤔",
  "Absolute Returns 💹",
  "[x] - Absurdism 🤪",
  "[x] - Abundance 🌟💰",
  "[x] - Activism ✊📢",
  "[x] - Addiction ⛓️🚬",
  "[x] - Aestheticism 🎨🌸",
  "Animism 🌳🌞",
  "[x] - ARG 🕵️‍♂️🔍",
  "[x] - Art-Products 🎨🛍️",
  "As I Lay Dying 💀📖",
  "Autofiction 📚📝",
  "[x] - Avant NFTs 🎨🔗💻",
  "[x] - Background 🎨🖼️",
  "[x] - Bad Marketing 🤦‍♂️📢",
  "[x] - Botany 🌱🔬",
  "[x] - Brand 🏷️👥",
  "[x] - Brand Line 🏷️👕",
  "Capital Violence 💣💰",
  "[x] - Casinos 🎰🃏",
  "[x] - Certification 📜📝",
  "[x] - Children's Stories 📚👧👦",
  "[x] - Choose Your Own Adventure 📚🚶‍♂️⚡️",
  "[x] - Cigarette Smuggling 🚬🚤🚫",
  "[x] - Commercialism 💰🛍️",
  "[x] - Commodities 💰📦",
  "[x] - Complex Emergence 🔄🌌",
  "Collapse 💥🏚️",
  "Concepts 💡🤔",
  "Connection 🤝🌐",
  "[x] - Copypasta 📋🍝",
  "Corporate Social Responsibility 🏢🌍🤝",
  "Critique 📝🔎",
  "[x] - Cryptoagrarianism 🌱💰💻",
  "Currency 💵💱",
  "Cuteness 😻🌸",
  "Cybernetics 🌐🧠",
  "[x] - Desiring-Production 💭🏭",
  "Derivatives ➗📊",
  "Digital Identity - 💻",
  "Dopamine 🔥",
  "Ecoterrorism 🌿💣",
  "Endless Grasping 🤲",
  "Ephemerality ⏳",
  "Eternalism ♾️",
  "Exporting Democracy 🗽🌍",
  "Eyes 👀",
  "Fading Individualism 🕴️",
  "Flame Wars 🔥🗡️",
  "Flowerpunk 🌸🤘",
  "Foil 🍽️",
  "Friendship 🤝❤️",
  "GANs 🖼️🧠",
  "Gazing into the Abyss 👁️🕳️",
  "Going Corporate 🏢💼",
  "Grateful Dead ⚡🌹",
  "Grey Markets 📦🌐",
  "Guy Debord 🎭📺",
  "Hyperfinancialization 💸📈",
  "Icebergs 🏔️❄️",
  "Identity-Consumption 🧑‍💼🛒",
  "Improv 🎭🎤",
  "Indulgence 🍰😋",
  "Interactive Theatre 🎭🎮",
  "Interning 📚👩‍💼",
  "Inversion ⬇️⬆️",
  "Investment Fund Mysticism 💼🔮",
  "Jean Lutgin 📚🔍",
  "John Boyd ✈️🛡️",
  "LBOs 💼💰",
  "Leaks 💦🔍",
  "Lifestyle Marketing 🛍️🎯",
  "Literary Salons 📚🍷💬",
  "Local Maxima 🏔️📈",
  "Mapacho 🚬🌿",
  "Market Expansion 📈🌍",
  "Marshall McLuhan 📺🔮",
  "Matryoshka Dolls 🎎🪆",
  "McMindfulness 🧘‍♀️💭",
  "MediaWiki 📚🌐",
  "Memes 🐸🖼️",
  "Metamodernism 🔄🎭",
  "Milady Maker 👸🔧",
  "Mircea Eliade 📚🌌",
  "Mock Ups 🖼️🎨",
  "MVPs 🏆👩‍💻",
  "Mycology 🍄🔬",
  "Naked Lunch 🍽️🐜",
  "Nervous System Regulation 🧠💆‍♀️",
  "Network Tribes 🌐👥",
  "Nihilism 🌑🤷‍♂️",
  "NikeID 👟🆔",
  "1988 Twin Peaks Pitch to ABC 🌲🏔️📺",
  "Nomadic Plains 🏞️🏕️",
  "Nusainq 🏞️🌅",
  "Oral Tradition 🗣️📜",
  "Overintellectualizing 🤯📚",
  "Ozymandias 🗿👑",
  "Pale Fire 🔥📖",
  "PFPs 🖼️🖼️",
  "Placebo 💊🙅‍♂️",
  "Pleasure 😊🎉",
  "PMC Jihad 💼⚔️",
  "Poetry 📜✍️",
  "Prestige TV 📺🏆",
  "Prison 🏢🔒",
  "Prometheus 🔥🧑‍🚀",
  "Prophylactics 🩺🔒",
  "R.A. Radford 📚🔍",
  "Rebirth ♻️👶",
  "Reflection 🌅🤔",
  "Richard Prince 🖼️👑",
  "RJR Nabisco 🚬💼",
  "RPG 🎲🧙‍♂️",
  "Scrapbooking 📔✂️",
  "Sensory Disciplinary Rituals 🧠🔮🪄",
  "Shoqanaw 🏞️🌳",
  "Simulacra 🎭🖼️",
  "Socializing 🤝🗣️",
  "Soulcycle Cultism 🚴‍♀️🔮",
  "Spiritual Colonialism 🌍⛪️",
  "Stepping Outside 🚶‍♀️🌳",
  "Subversion ⬇️",
  "Supply Chains ⛓️📦",
  "Symbolic Hijacking 🚩🔒",
  "Synthetic Uncoupling 🧪💔",
  "SWOT 📊✅❌",
  "Taste 👅🍽️",
  "Tastelessness 🤢🚫",
  "Tax Stamp 💰🧾",
  "Theory 📚🤔",
  "Trend Forecasting 📈🔮",
  "Tojiba CPU Corp 💻🏢",
  "Trinkets 💍🎁",
  "Truth Tobacco Industry Documents 📜💨",
  "Tttt.ru 💻🚬🌐",
  "Vajrayana 🕉️📿",
  "Viktor Frankl 📚🧠",
  "Violence 🔪💥",
  "Virginia and Baltick Coffee House ☕️🏛️",
  "Vladislav Surkov 🎭🎪",
  "Walter Benjamin 📚🕰️",
  "War 💣",
  "Waxing Languorously 🕯️😌",
  "Warning Labels ⚠️🏷️",
];

export const titler = () => {
  return possibleTitles[Math.floor(Math.random() * possibleTitles.length)];
};
